### ISSUE TITLE
DOM Exception 12 in Safari within corner_init

### ISSUE THREAD

**Issue by dotstormz** [Jabher/cornerjs#6]
```
[Error] SyntaxError: DOM Exception 12: An invalid or illegal string was specified.
	observe (bundle.js:9673)
	corner_init (bundle.js:9673)
```

Getting this in Safari 9, even if I don't trigger any `directive()` calls. Any ideas?

**Comment by Jabher** [comment]
Looks like I was poorly following the spec, and Safari decided to strict their parser.
https://github.com/Jabher/cornerjs/blob/master/src/corner.js#L102 - 'attributes' should be here instead of 'attribute'. Can you please create a PR for that?
